[build]
  base = "uiG"
  command = "npm install && npm run build"
  publish = "uiG/dist"

# IMPORTANT: explicitly disable functions
[functions]
  directory = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
